---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/ar-enum.rb
    - vendor/**/*
    - gemfiles/**/*

Layout/LineLength:
  Enabled: false
