---
language: ruby
dist: xenial
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
cache: bundler
before_install:
  - gem install bundler
  - sudo service postgresql stop
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo service postgresql start 11
before_script:
  - createdb ar_enum_test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
gemfile:
  - gemfiles/activerecord_6_0.gemfile
  - gemfiles/activerecord_5_2.gemfile
rvm:
  - 2.6.5
  - 2.5.7
notifications:
  email: false
env:
  global:
    secure: ItWMub2Jbp/Xey50SAPWeYzZcKoEFORj716NmbQI1NbnOzqEDOF3pDZd9HHCxHoBA6gYYDIGWFCa15ymfugzBJ/eGaL7qzEF098xU7hwgG0DOlU31RAPOwn7ov3merGVJOttWOgYYmTR7pxyyg5iMc7/IzU5ag1As+Sz8s7vq9uR2HRdRALvuRFAS1Vty5lV1dINVNIs2vSHMIdgwWCaraWno8R3WupchXgkoA4WGwK6+n99ZUfuCv6kLwAJhlH3rWXEuwT49ILGRCYUp3rRZ/wawclUviYjxgVvS5xeEGzsh3X9AMkbq68up9zxcG1KYeL+EKxLDL6ieC2OtaqMst3k7UariK5QWro00TdGdNpw2M83d0ca81PUW8lpyZVvOJ8STDFR3Dtt8emaz/F0rHiBJlMP1vKWYxgQgpIEIv+WQV2YcVJBg0NNjQ8Ei6ujGG2s8pJNvJBudK/jL3okpXy/uPd5djQfoJcLnZk0xHOqJtcr1+Xg/9TUo/vh81U8cIgGJDtwssoyMastqv1U9Gm2AfsRKmjDyRoIhvwbF9V3dpdks4tRtmnEoYo91K9y2nv45tyO0R6PSEhNL8wDGlvgqUk4XlaaQEs2yNPgpX07ivs47+/x8ufkcyzAf0nHXN/FDzqLnHQBHqdk8a/BTY9wWQP1d5iIuojr30vR4X4=
